apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.service.name }}
subsets:
  - addresses:
      {{- range .Values.endpoints }}
      - ip: {{ .ip }}
      {{- end }}
    ports:
      - port: {{ .Values.service.targetPort }} 