apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.service.name }}
subsets:
  - addresses:
    {{- range .Values.backendEndpoints }}
    - ip: {{ .ip }}
    {{- end }}
    ports:
      - port: {{ .Values.backendEndpoints.port | default 5173 }}
