apiVersion: v1
kind: Pod
metadata:
  name: resource-hog
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        memory: "500Gi"
        cpu: "1000"
      limits:
        memory: "500Gi"
        cpu: "1000"
