apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-demo
  template:
    metadata:
      labels:
        app: secret-demo
    spec:
      containers:
        - name: demo-container
          image: busybox
          command:
            - "sh"
            - "-c"
            - |
              echo "### Keskkonnamuutujad ###";
              echo "DB_USERNAME=$DB_USERNAME";
              echo "DB_PASSWORD=$DB_PASSWORD";
              echo "";
              echo "### Failid (volume) ###";
              ls /etc/secret;
              echo "username: $(cat /etc/secret/username)";
              echo "password: $(cat /etc/secret/password)";
              sleep 3600
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secret"
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: db-secret
