{{- if .Values.alertmanager.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring-stack.alertmanager.fullname" . }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "monitoring-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      {{- with .Values.alertmanager.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monitoring-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
    spec:
      {{- with .Values.alertmanager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "monitoring-stack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.alertmanager.podSecurityContext | nindent 8 }}
      containers:
        - name: alertmanager
          securityContext:
            {{- toYaml .Values.alertmanager.securityContext | nindent 12 }}
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
          args:
            - --config.file=/etc/alertmanager/config.yaml
            - --storage.path=/alertmanager
          ports:
            - name: web
              containerPort: 9093
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
            initialDelaySeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
            - name: storage-volume
              mountPath: /alertmanager
          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "monitoring-stack.alertmanager.fullname" . }}
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ include "monitoring-stack.alertmanager.fullname" . }}
      {{- with .Values.alertmanager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.alertmanager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
