{{- if (get .Values "fluent-bit").enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-fluent-bit
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: fluent-bit
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
{{- end }}
