{{- if (get .Values "fluent-bit").enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-fluent-bit
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: fluent-bit
spec:
  selector:
    matchLabels:
      {{- include "monitoring-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: fluent-bit
  template:
    metadata:
      labels:
        {{- include "monitoring-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: fluent-bit
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2021"
        prometheus.io/path: "/api/v1/metrics/prometheus"
    spec:
      serviceAccountName: {{ include "monitoring-stack.fullname" . }}-fluent-bit
      containers:
        - name: fluent-bit
          image: "{{ (get .Values "fluent-bit").image.repository }}:{{ (get .Values "fluent-bit").image.tag }}"
          imagePullPolicy: {{ (get .Values "fluent-bit").image.pullPolicy }}
          args:
            - -c
            - /fluent-bit/etc/fluent-bit.conf
          resources:
            {{- toYaml (get .Values "fluent-bit").resources | nindent 12 }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/
          ports:
            - name: metrics
              containerPort: 2021
              protocol: TCP
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: {{ include "monitoring-stack.fullname" . }}-fluent-bit
{{- end }}
