{{- if .Values.kibana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-kibana
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "monitoring-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
{{- end }}
