{{- if .Values.kubeStateMetrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-stack.fullname" . }}-kube-state-metrics
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    component: kube-state-metrics
  {{- with .Values.kubeStateMetrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.kubeStateMetrics.service.type }}
  ports:
    - port: {{ .Values.kubeStateMetrics.service.port }}
      targetPort: {{ .Values.kubeStateMetrics.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "monitoring-stack.selectorLabels" . | nindent 4 }}
    component: kube-state-metrics
{{- end }} 