{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring-stack.prometheus.fullname" . }}-rules
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "monitoring-stack.prometheus.labels" . | nindent 4 }}
    prometheus-rules: "true"
data:
  node-alerts.yaml: |
    groups:
    - name: node-alerts
      rules:
      - alert: HighCpuUsage
        expr: clamp_max((100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=~".*monitoring-stack.*",mode="idle"}[5m])) * 100)) * 2, 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on node {{`{{`}}$labels.instance{{`}}`}}"
          description: "Node CPU usage is at {{`{{`}} printf \"%.2f\" $value {{`}}`}}% for more than 5 minutes."
      - alert: LowDiskSpace
        expr: node_filesystem_avail_bytes{mountpoint="/mnt/testdisk"} / node_filesystem_size_bytes{mountpoint="/mnt/testdisk"} * 100 < 20
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space on node {{`{{`}}$labels.instance{{`}}`}}"
          description: "Node available disk space is at {{`{{`}} printf \"%.2f\" $value {{`}}`}}%."
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on node {{`{{`}}$labels.instance{{`}}`}}"
          description: "Node memory usage is at {{`{{`}} printf \"%.2f\" $value {{`}}`}}% for more than 5 minutes."

  pod-alerts.yaml: |
    groups:
    - name: pod-alerts
      rules:
      - alert: PodRestartingTooFrequently
        expr: changes(kube_pod_container_status_restarts_total[15m]) > 3
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Pod {{`{{`}}$labels.pod{{`}}`}} in namespace {{`{{`}}$labels.namespace{{`}}`}} is restarting too frequently"
          description: "Pod {{`{{`}}$labels.pod{{`}}`}} (container {{`{{`}}$labels.container{{`}}`}}) has restarted more than 3 times in the last 15 minutes."
      - alert: PodMemoryUsageHigh
        expr: sum(container_memory_usage_bytes{pod!="", container!=""}) by (pod, namespace) / sum(kube_pod_container_resource_limits_memory_bytes) by (pod, namespace) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage for pod {{`{{`}}$labels.pod{{`}}`}} in namespace {{`{{`}}$labels.namespace{{`}}`}}"
          description: "Pod memory usage is at {{`{{`}} printf \"%.2f\" $value {{`}}`}}% of its limit."
      - alert: PodPendingTooLong
        expr: kube_pod_status_phase{phase="Pending"} == 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Pod {{`{{`}}$labels.pod{{`}}`}} in namespace {{`{{`}}$labels.namespace{{`}}`}} is pending"
          description: "Pod {{`{{`}}$labels.pod{{`}}`}} has been in a pending state for more than 5 minutes."

  cluster-alerts.yaml: |
    groups:
    - name: cluster-alerts
      rules:
      - alert: KubernetesApiServerDown
        expr: up{job="kubernetes-apiservers"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kubernetes API server is down"
          description: "The Kubernetes API server is unreachable."

  monitoring-logging-alerts.yaml: |
    groups:
    - name: monitoring-logging-alerts
      rules:
      - alert: ElasticsearchClusterStatusYellow
        expr: elasticsearch_cluster_health_status{color="yellow"} == 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Elasticsearch cluster status is yellow"
          description: "Elasticsearch cluster {{`{{`}}$labels.cluster{{`}}`}} is in yellow status."
      - alert: ElasticsearchClusterStatusRed
        expr: elasticsearch_cluster_health_status{color="red"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Elasticsearch cluster status is red"
          description: "Elasticsearch cluster {{`{{`}}$labels.cluster{{`}}`}} is in red status."
      - alert: FluentdLogCollectionErrors
        expr: fluentd_log_errors_total > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Fluentd log collection errors"
          description: "Fluentd is experiencing log collection errors."
{{- end }}