{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring-stack.prometheus.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "monitoring-stack.prometheus.labels" . | nindent 4 }}
{{- end }}
