apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "elasticsearch.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "elasticsearch.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "elasticsearch.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: cluster.name
              value: {{ .Release.Name }}
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "{{ include "elasticsearch.fullname" . }}-0.{{ include "elasticsearch.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local,{{ include "elasticsearch.fullname" . }}-1.{{ include "elasticsearch.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
            - name: cluster.initial_master_nodes
              value: "{{ include "elasticsearch.fullname" . }}-0,{{ include "elasticsearch.fullname" . }}-1"
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          {{- end }}
        - name: elasticsearch-exporter
          image: prometheuscommunity/elasticsearch-exporter
          args:
            - "--es.uri=http://localhost:9200"
            - "--es.all"
            - "--es.indices"
            - "--es.shards"
          ports:
            - name: metrics
              containerPort: 9114
              protocol: TCP
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}
