apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-frontend.fullname" . }}
  labels:
    {{- include "metrics-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "metrics-frontend.selectorLabels" . | nindent 4 }}
---
{{- if eq .Values.service.type "ClusterIP" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-frontend.fullname" . }}-nodeport
  labels:
    {{- include "metrics-frontend.labels" . | nindent 4 }}
    service-type: nodeport
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "metrics-frontend.selectorLabels" . | nindent 4 }}
{{- end }}