apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # Image Updater spetsiifilised õigused
    p, role:image-updater, applications, get, *, allow
    p, role:image-updater, applications, update, *, allow
    p, role:image-updater, applications, sync, *, allow
    p, role:image-updater, applications, action/*, *, allow
    p, role:image-updater, repositories, get, *, allow
    p, role:image-updater, repositories, update, *, allow
    p, role:image-updater, repositories, create, *, allow
    p, role:image-updater, certificates, get, *, allow
    
    # Määra image-updater kasutajale roll
    g, image-updater, role:image-updater
    
    # Admin rolli säilitamine
    g, admin, role:admin
