service:
  name: metrics-frontend
  port: 80
  targetPort: 5173
  type: ClusterIP

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: metrics.local
      paths:
        - path: /
          pathType: Prefix 