# Default values for metrics-backend
replicaCount: 1

image:
  repository: tanelsokolov/metrics-backend
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 0

securityContext:
  runAsNonRoot: false
  runAsUser: 0
  capabilities:
    add:
    - SYS_ADMIN
    - DAC_OVERRIDE

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: false
  monitoring:
    enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: metrics-backend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

logging:
  level: info
  format: json

cors:
  origin: "*"
  methods: "GET,POST,PUT,DELETE,OPTIONS"

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 10m 
    memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables
env:
  PORT: "3000"
  NODE_ENV: "production"

# ConfigMap data
config: {}

# Health check settings
healthCheck:
  enabled: true
  path: /health
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
  readinessInitialDelaySeconds: 20
  readinessPeriodSeconds: 10

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1