# Production environment values for metrics-backend

replicaCount: 2

image:
  repository: metrics-backend
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  NODE_ENV: "production"
  PORT: "3000"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  nodePort: 30301

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: metrics-backend.company.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: metrics-backend-tls
      hosts:
        - metrics-backend.company.com

logging:
  level: info

cors:
  origin: "*"

# Enable autoscaling in production
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Enable PDB for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Production monitoring annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"
  prometheus.io/path: "/metrics"