# Production environment values for metrics-backend

replicaCount: 2

image:
  repository: tanelsokolov/metrics-backend
  pullPolicy: Always
  tag: "prod-latest"

env:
  NODE_ENV: "production"
  PORT: "3000"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  nodePort: 30301

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: metrics-backend-prod.local
      paths:
        - path: /
          pathType: Prefix

logging:
  level: info
  format: json

cors:
  origin: "*"
  methods: "GET,POST,PUT,DELETE,OPTIONS"


# Enable autoscaling in production
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Enable PDB for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Production monitoring annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"
  prometheus.io/path: "/metrics"