apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: 
    argocd-image-updater.argoproj.io/frontend.helm.image-spec: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/git-commit-user: argocd-image-updater
    argocd-image-updater.argoproj.io/git-commit-email: argocd-image-updater@tanelsokolov.dev
    argocd-image-updater.argoproj.io/git-commit-message: "chore: update {{.AppName}} frontend image to {{.NewTag}}"

spec:
  project: default
  source:
    repoURL: https://github.com/tanelsokolov/k8m
    targetRevision: main
    path: charts/metrics-frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
