apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-backend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tanelsokolov/k8
    targetRevision: main
    path: charts/metrics-backend
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true