apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-backend-prod
  namespace: argocd
  annotations:
    # Image Updater konfiguratsiooni annotaatsioonid
    argocd-image-updater.argoproj.io/image-list: backend=tanelsokolov/metrics-backend
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    
    # Timestamp-based versioning (mitte semantic versioning)
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^prod-[0-9]{8}-[0-9]{6}$
    argocd-image-updater.argoproj.io/backend.ignore-tags: latest,dev-latest,dev-.*
    
    # Git commit seaded
    argocd-image-updater.argoproj.io/git-commit-user: argocd-image-updater
    argocd-image-updater.argoproj.io/git-commit-email: argocd-image-updater@tanelsokolov.dev
    argocd-image-updater.argoproj.io/git-commit-message: "chore: update {{.AppName}} backend image to {{.NewTag}}"
spec:
  project: default
  source:
    repoURL: https://github.com/tanelsokolov/k8m
    targetRevision: main
    path: charts/metrics-backend
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true