# Default values for metrics-frontend
replicaCount: 2

image:
  repository: tanelsokolov/metrics-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  readOnlyRootFilesystem: false

service:
  type: LoadBalancer
  port: 80
  targetPort: 5173

ingress:
  enabled: true
  monitoring:
    enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: metrics-frontend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

logging:
  level: info
  format: json

cors:
  origin: "*"
  methods: "GET,POST,PUT,DELETE,OPTIONS"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables
env:
  PORT: "5173"
  NODE_ENV: "production"
  BACKEND_URL: "http://metrics-backend.monitoring-dev.svc.cluster.local:3000"

# frontend service configuration
frontend:
  serviceName: "metrics-frontend"
  servicePort: 5173
  # For dev: use external IP, for prod: use internal service
  externalUrl: "http://192.168.189.101"
  useInternalService: false

# ConfigMap data for frontend configuration
config:
  api:
    baseUrl: "http://metrics-frontend.default.svc.cluster.local:5173"
    metricsEndpoint: "/metrics"
    timeout: "5000"
  dashboard:
    title: "Metrics Dashboard"
    refreshInterval: 30000
    theme: "dark"
    showDebug: false
  features:
    enableDebugMode: false
    enableMockData: false
    enablePerformanceMetrics: true
    showDeveloperTools: false


# Health check settings
healthCheck:
  enabled: true
  path: /health
  port: 5173
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
  readinessInitialDelaySeconds: 5
  readinessPeriodSeconds: 10

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1